FROM cbcrg/ampa-nf 


RUN wget -q --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-linux-x64.tar.gz; \
  tar xf jdk-8u25-linux-x64.tar.gz -C /opt; \
  rm -f jdk-8u25-linux-x64.tar.gz; 
  
RUN curl -fsSL get.nextflow.io | bash; \
  nextflow -download; \
  cp nextflow /usr/local/bin
    
ENV JAVA_HOME /opt/jdk1.8.0_25
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin:/opt/jdk1.8.0_25/bin